name: ldasoft-global-fit

# Goal of this is to provide a conda environment that works
# WITH the environment on a compute node to allow ldasoft/mbh
# to be built with the compute nodes libs available at compile time
#
# Entering this env should look something like
# module load cmake/<version>
# module load ompi/<version> (which may also load ucx/gcc)
# module load gcc/<version>
#
# conda activate ldasoft-global-fit
#
# It is desirable that this env not directly contain a compiler, but if it is unavoidable an additional bypass will be needed
# We want to use/find Hyak compute node compiler and MPI wrapper
#
#
channels:
        - defaults
        - conda-forge
dependencies:
        - conda-forge::gsl
        - conda-forge::hdf5[build=mpi_openmpi*]
        - conda-forge::libopenblas[build=openmp*]
